//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdfinder.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdfinder.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About mdfinder....
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdfinder is a file scanning and hashing application..
        /// </summary>
        public static string AboutWindowDescription {
            get {
                return ResourceManager.GetString("AboutWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github.
        /// </summary>
        public static string AboutWindowGithubLinkLabel {
            get {
                return ResourceManager.GetString("AboutWindowGithubLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string AboutWindowLicenseLinkLabel {
            get {
                return ResourceManager.GetString("AboutWindowLicenseLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About mdfinder.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Remaining Files.
        /// </summary>
        public static string ActionArchiveLabel {
            get {
                return ResourceManager.GetString("ActionArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Actions.
        /// </summary>
        public static string ActionBarLabel {
            get {
                return ResourceManager.GetString("ActionBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Largest.
        /// </summary>
        public static string ActionLargestLabel {
            get {
                return ResourceManager.GetString("ActionLargestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeepSelected.
        /// </summary>
        public static string ActionSelectedLabel {
            get {
                return ResourceManager.GetString("ActionSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Smallest.
        /// </summary>
        public static string ActionSmallestLabel {
            get {
                return ResourceManager.GetString("ActionSmallestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Folder.
        /// </summary>
        public static string ArchiveFolderLabel {
            get {
                return ResourceManager.GetString("ArchiveFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to visit mdfinder to update to the latest version?.
        /// </summary>
        public static string BehindVersionQuestion {
            get {
                return ResourceManager.GetString("BehindVersionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is behind the github repository and should be updated..
        /// </summary>
        public static string BehindVersionStatusDescription {
            get {
                return ResourceManager.GetString("BehindVersionStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bin size must be greater than or equal to 1 and less than [int max | todo: find out the actual value]..
        /// </summary>
        public static string BinSizeOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("BinSizeOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type to {0} from or to a boolean..
        /// </summary>
        public static string BooleanInvalidCastExceptionFormat {
            get {
                return ResourceManager.GetString("BooleanInvalidCastExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearLabel {
            get {
                return ResourceManager.GetString("ClearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep File.
        /// </summary>
        public static string ColumnHeaderKeep {
            get {
                return ResourceManager.GetString("ColumnHeaderKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        public static string ColumnHeadingHash {
            get {
                return ResourceManager.GetString("ColumnHeadingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Provider.
        /// </summary>
        public static string ColumnHeadingHashProvider {
            get {
                return ResourceManager.GetString("ColumnHeadingHashProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ColumnHeadingPath {
            get {
                return ResourceManager.GetString("ColumnHeadingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ColumnHeadingSize {
            get {
                return ResourceManager.GetString("ColumnHeadingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is up to date with the github repository..
        /// </summary>
        public static string CurrentVersionStatusDescription {
            get {
                return ResourceManager.GetString("CurrentVersionStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is ahead of the github repository, or is a custom version of butterflow-ui that cannot be compared to the github repository..
        /// </summary>
        public static string CustomVersionStatusDescription {
            get {
                return ResourceManager.GetString("CustomVersionStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md5 hash provider. This provider creates a simple md5 hash given a file..
        /// </summary>
        public static string DefaultHashProviderDescription {
            get {
                return ResourceManager.GetString("DefaultHashProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Provider.
        /// </summary>
        public static string DefaultHashProviderName {
            get {
                return ResourceManager.GetString("DefaultHashProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers and Contributors.
        /// </summary>
        public static string DevelopersLabel {
            get {
                return ResourceManager.GetString("DevelopersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Processing Threshold.
        /// </summary>
        public static string FileAlertThresholdLabel {
            get {
                return ResourceManager.GetString("FileAlertThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FilesLabel {
            get {
                return ResourceManager.GetString("FilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Files.
        /// </summary>
        public static string ItemsLabel {
            get {
                return ResourceManager.GetString("ItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default MD5 hash provider should not have its priorty set..
        /// </summary>
        public static string MD5ProviderSetPriorityException {
            get {
                return ResourceManager.GetString("MD5ProviderSetPriorityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Preview Available.
        /// </summary>
        public static string NoPreviewLabel {
            get {
                return ResourceManager.GetString("NoPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not A Duplicate.
        /// </summary>
        public static string NotDupliateLabel {
            get {
                return ResourceManager.GetString("NotDupliateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Database....
        /// </summary>
        public static string OpenMenuItem {
            get {
                return ResourceManager.GetString("OpenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Libraries.
        /// </summary>
        public static string OpenSourceCreditsLabel {
            get {
                return ResourceManager.GetString("OpenSourceCreditsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Changing the user language will require a restart of the program..
        /// </summary>
        public static string OptionsWindowLanguageChangeNotice {
            get {
                return ResourceManager.GetString("OptionsWindowLanguageChangeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Space Savings.
        /// </summary>
        public static string PotentialSpaceSavingsLabel {
            get {
                return ResourceManager.GetString("PotentialSpaceSavingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Location.
        /// </summary>
        public static string ProviderFolderLabel {
            get {
                return ResourceManager.GetString("ProviderFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File Database....
        /// </summary>
        public static string SaveMenuItem {
            get {
                return ResourceManager.GetString("SaveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string ScanLabel {
            get {
                return ResourceManager.GetString("ScanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location to Scan.
        /// </summary>
        public static string ScanLocationLabel {
            get {
                return ResourceManager.GetString("ScanLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Location.
        /// </summary>
        public static string ScanningLabel {
            get {
                return ResourceManager.GetString("ScanningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the selected path.
        /// </summary>
        public static string ScanTooltip {
            get {
                return ResourceManager.GetString("ScanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size On Disk:.
        /// </summary>
        public static string SizeOnDiskLabel {
            get {
                return ResourceManager.GetString("SizeOnDiskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Empty Files.
        /// </summary>
        public static string SkipEmptyFilesLabel {
            get {
                return ResourceManager.GetString("SkipEmptyFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdfinder.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github failed to respond with the current version. This could be because of rate limits or a network failure..
        /// </summary>
        public static string UnknownVersionStatusDescription {
            get {
                return ResourceManager.GetString("UnknownVersionStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
